### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by talhaanwarch** [SpicyYeol/Pytorch_rppgs#1]
Can you upload pre-trained model?

**Comment by SpicyYeol** [comment]
We will give pre-trained model with a google drive link befor 6.pm on Friday in Korean time.

Thanks for your interest.

**Comment by SpicyYeol** [comment]
But, It should be noted that we are still implementing and experimenting.

**Comment by jinsoogod** [comment]
[https://drive.google.com/drive/folders/1EBcJy3qruRL4AtY2EgZqsv8g97f65Je6?usp=sharing](url)
Model trained COHFACE data

**Comment by ivylinden** [comment]
Hello, Where can I find the pre-trained model
